name: Bug Report
description: Report a bug in Aspire.Hosting.Minecraft
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: input
    id: title
    attributes:
      label: Summary
      description: A brief summary of the bug.
      placeholder: e.g. RCON connection drops after 60 seconds
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A detailed description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Add Minecraft server resource to Aspire AppHost
        2. Start the application
        3. Observe the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment.
      placeholder: |
        - OS: Windows 11 / Ubuntu 24.04 / macOS 15
        - .NET SDK version: 10.0.100
        - Package version: 0.1.0
        - Docker version (if applicable): 27.x
    validations:
      required: true
