name: Feature Request
description: Suggest a new feature for Aspire.Hosting.Minecraft
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the information below.

  - type: input
    id: title
    attributes:
      label: Summary
      description: A brief summary of the feature.
      placeholder: e.g. Support for Fabric mod loader
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A detailed description of the feature you'd like to see.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the problem or scenario this feature would address.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe how you think this feature could be implemented.
    validations:
      required: false
